services:
  ftp:
    image: stilliard/pure-ftpd
    container_name: ftp
    hostname: ftp
    restart: always
    networks:
      - mysql-net
    ports:
      - "21:21"
      - "30000-30009:30000-30009"
    environment:
      FTP_USER_NAME: ftpuser
      FTP_USER_PASS: ftppassword
      FTP_USER_HOME: /home/ftpuser
    volumes:
      - "/home/tekimp/DockerNetwork/static/data:/home/ftpuser"
      - "/home/tekimp/DockerNetwork/static/passwd:/etc/pure-ftpd/passwd"

  apache:
    image: httpd:latest
    container_name: apache
    hostname: apache
    restart: always
    networks:
      - mysql-net
    ports:
      - "8081:80"
    volumes:
      - "/home/tekimp/DockerNetwork/static/data:/usr/local/apache2/htdocs:ro"

networks:
  mysql-net:
    external: true
    name: mysql-net